CREATE SCHEMA IF NOT EXISTS test_issue AUTHORIZATION sample;

CREATE FUNCTION add_priority()  
RETURNS INTEGER  
AS  
$$  
DECLARE M INTEGER;
BEGIN  
select MAX(priority) INTO M from test_issue.goods; 
IF M IS NULL THEN
M = 0;
END IF;
RETURN M+1;  
END;
$$
LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS test_issue.projects (
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name text,
created_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS test_issue.goods (
id integer GENERATED BY DEFAULT AS IDENTITY,
project_id integer,
name text,
description text,
priority integer DEFAULT add_priority(),
removed bool DEFAULT false,
created_at timestamp DEFAULT now(),
CONSTRAINT goods_pk PRIMARY KEY(id,project_id)
);